### ISSUE TITLE
includes not found

### ISSUE THREAD

**Issue by xpunkt** [tomarus/nntpswitch#1]
json-c/json.h is json/json.h on gentoo global include, i tryed finding radlib.h but to no awail its maybe an error in radlib ebuild it does not install the header includes ?

radlib have

/usr/include/radUDPsocket.h
/usr/include/radbuffers.h
/usr/include/radconffile.h
/usr/include/radcrc.h
/usr/include/raddatabase.h
/usr/include/raddebug.h
/usr/include/radevents.h
/usr/include/radlist.h
/usr/include/radmsgLog.h
/usr/include/radmsgRouter.h
/usr/include/radprocess.h
/usr/include/radproclist.h
/usr/include/radprocutils.h
/usr/include/radqueue.h
/usr/include/radsemaphores.h
/usr/include/radsha.h
/usr/include/radshmem.h
/usr/include/radsocket.h
/usr/include/radsortlist.h
/usr/include/radstack.h
/usr/include/radstates.h
/usr/include/radsysdefs.h
/usr/include/radsystem.h
/usr/include/radsysutils.h
/usr/include/radtextsearch.h
/usr/include/radthread.h
/usr/include/radtimeUtils.h
/usr/include/radtimers.h

**Comment by tomarus** [comment]
You should install the linux libradius library: http://portal-to-web.de/tacacs/libradius.php (Also install libmd from the same page).

NNTPSwitch is not compatbile with other radius libraries.
